### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by zkt2002** [powerjett/react-code#2]
\react-code\scripts\start.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\util\createHash.js:135:53)        
    at NormalModule._initBuildHash (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at context.callback (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:111:13)   
    at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by jett6680** [comment]
请问node版本是多少呢

**Comment by jett6680** [comment]
> \react-code\scripts\start.js:11 throw err; ^
> 
> Error: error:0308010C:digital envelope routines::unsupported at new Hash (node:internal/crypto/hash:71:19) at Object.createHash (node:crypto:133:10) at module.exports (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\util\createHash.js:135:53) at NormalModule._initBuildHash (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:417:16) at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:452:10 at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:323:13 at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:367:11 at context.callback (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:111:13) at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\babel-loader\lib\index.js:59:103 { opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' }

请问node版本多少呢

**Comment by jett6680** [comment]
> \react-code\scripts\start.js:11 throw err; ^
> 
> Error: error:0308010C:digital envelope routines::unsupported at new Hash (node:internal/crypto/hash:71:19) at Object.createHash (node:crypto:133:10) at module.exports (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\util\createHash.js:135:53) at NormalModule._initBuildHash (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:417:16) at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:452:10 at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\webpack\lib\NormalModule.js:323:13 at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:367:11 at context.callback (C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\loader-runner\lib\LoaderRunner.js:111:13) at C:\Users\zkt\Desktop\面试\前端框架原理\react-code\node_modules\babel-loader\lib\index.js:59:103 { opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' }

我这边复现了这个问题，你应该使用的node版本是 >= 18的 ， 需要使用node 14 或者 16

**Comment by zkt2002** [comment]
哦哦，是的，我的node版本是18+的，谢谢你
